version: '3'

services:
  go-spark-change:
    image: golang:1.22.0
    container_name: go-create-change
    environment:
      - TEST_SLACK=${TEST_SLACK}
    volumes:
      - ${PWD}:/src
    working_dir: /src
    entrypoint:
      - /bin/sh
      - -c
      - |
        go run createSpark.go